### ISSUE TITLE
Sparse matrix

### ISSUE THREAD

**Issue by Kvaz1r** [nyorain/nytl#15]
I guess implementation of sparse matrix will be good addition for matrix-vectors classes.

**Comment by nyorain** [comment]
Thanks, will write that on my list, not so sure though how this would fit into the current implementation.
I hadn't much time lately but will try to resume nytl development in the next time and there are other changes to be applied first like finishing unit testing and fixing remaining bugs as well as updating to C++17.

**Comment by nyorain** [comment]
Currently cleaning up all of the mess i wrote over the years. The approach of nytl was too generic to be simple, i reworked it and it is not intended to work with special needs such as a sparse marix for now.

I implemented an example for this some time ago (the generic-mat branch) but for now this will not happen, the focus of nytl is on simplicity.
