### ISSUE TITLE
Add conan package

### ISSUE THREAD

**Issue by Alxandr** [nyorain/nytl#16]
I'm installing all my dependencies from conan, and could not find a conan package for nytl. I know it's only headers, but that doesn't mean it can't be distributed using conan :).

**Comment by nyorain** [comment]
Have never used conan before, but would be nice if people actually use it.
How would it be done? This project will probably switch to meson soon (see the meson branch), is there any way to get it work with conan?

**Comment by Alxandr** [comment]
I don't know what meson is (I've almost never done C/C++). Setting up conan "building" should probably be pretty easy (especially given that this project only has headers), though I don't know much about it. I've just read this: https://stackoverflow.com/questions/40311363/conan-io-header-only-package.

**Comment by nyorain** [comment]
yeah, doesn't look like too much work and since this doesn't have to build anything the build system should not matter in the end (meson is a buildsystem like cmake). Thanks for the pointer, will look into it soon.

**Comment by Alxandr** [comment]
I'm going to be brazen enough to ask maybe @dimi309 can help? He's recently made a PR to the glew repository with conan support.

**Comment by dimi309** [comment]
@nyorain would you be interested in a pull request with the conan packaging configuration? I can get around to putting it together in a couple of days.

**Comment by nyorain** [comment]
of course, thanks! I would probably need some time first digging into conan and maybe get things wrong on the first try.

**Comment by dimi309** [comment]
Very well! We'll do that then. By the way, the conan team has released an article about packaging header-only libraries:

http://docs.conan.io/en/latest/howtos/header_only.html

GLM is a header-only library for example, which I have already packaged:

https://github.com/g-truc/glm/tree/master/util/conan-package

So I'll do something similar for nytl and show you how you can publish the package on bintray.

**Comment by Alxandr** [comment]
@dimi309 lemme know if there is suddenly a temp nytl on your bintray feed 📦 :P

**Comment by dimi309** [comment]
Done! I have introduced the pull request:

https://github.com/nyorain/nytl/pull/17

I have not published the package on my bintray repository, but if you clone [my fork of nytl](https://github.com/dimi309/nytl) and run:

```
cd nytl/conan
conan create nyorain/stable
```

you can already use it :)

**Comment by Alxandr** [comment]
Great. I had to figure out cmake custom include folders previously just to get nytl working for me without changing the sources :P. Being new to C++ makes stuff like this incredibly frustrating. I can write the code alright, but I have no idea how to use the tools. Conan takes a good brunt of the pain away :)

**Comment by dimi309** [comment]
I hear you. Here's how you had to build my small3d library, before I stopped supporting non-conan builds:

https://github.com/dimi309/small3d/blob/701cbfabecefc3702ccaae7cdedeac24e3c00841/README.md

**Comment by nyorain** [comment]
Thanks guys!

**Comment by Alxandr** [comment]
@nyorain is it published anywhere? You should have travis autodeploy 📦 🚀 💯

**Comment by nyorain** [comment]
https://bintray.com/nyorain/nytl/nytl%3Anyorain/master%3Adev
Not sure if everything is named and labeled correctly but it works for now i guess.
Since this repo is currently not stable in any way it does probably not make much sense to automatically upload it at every change.
